package com.landicorp.yinshang.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.landicorp.yinshang.db.LoginRespBean;
import com.landicorp.yinshang.db.PayInfoBean;
import com.landicorp.yinshang.db.TransactionReqSubBean;

import com.landicorp.yinshang.db.LoginRespBeanDao;
import com.landicorp.yinshang.db.PayInfoBeanDao;
import com.landicorp.yinshang.db.TransactionReqSubBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginRespBeanDaoConfig;
    private final DaoConfig payInfoBeanDaoConfig;
    private final DaoConfig transactionReqSubBeanDaoConfig;

    private final LoginRespBeanDao loginRespBeanDao;
    private final PayInfoBeanDao payInfoBeanDao;
    private final TransactionReqSubBeanDao transactionReqSubBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginRespBeanDaoConfig = daoConfigMap.get(LoginRespBeanDao.class).clone();
        loginRespBeanDaoConfig.initIdentityScope(type);

        payInfoBeanDaoConfig = daoConfigMap.get(PayInfoBeanDao.class).clone();
        payInfoBeanDaoConfig.initIdentityScope(type);

        transactionReqSubBeanDaoConfig = daoConfigMap.get(TransactionReqSubBeanDao.class).clone();
        transactionReqSubBeanDaoConfig.initIdentityScope(type);

        loginRespBeanDao = new LoginRespBeanDao(loginRespBeanDaoConfig, this);
        payInfoBeanDao = new PayInfoBeanDao(payInfoBeanDaoConfig, this);
        transactionReqSubBeanDao = new TransactionReqSubBeanDao(transactionReqSubBeanDaoConfig, this);

        registerDao(LoginRespBean.class, loginRespBeanDao);
        registerDao(PayInfoBean.class, payInfoBeanDao);
        registerDao(TransactionReqSubBean.class, transactionReqSubBeanDao);
    }
    
    public void clear() {
        loginRespBeanDaoConfig.clearIdentityScope();
        payInfoBeanDaoConfig.clearIdentityScope();
        transactionReqSubBeanDaoConfig.clearIdentityScope();
    }

    public LoginRespBeanDao getLoginRespBeanDao() {
        return loginRespBeanDao;
    }

    public PayInfoBeanDao getPayInfoBeanDao() {
        return payInfoBeanDao;
    }

    public TransactionReqSubBeanDao getTransactionReqSubBeanDao() {
        return transactionReqSubBeanDao;
    }

}
